#
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Interpretation(object):
    def setupUi(self, Interpretation):
        Interpretation.setObjectName("Interpretation")
        Interpretation.resize(820, 561)
        self.verticalLayoutRoot = QtWidgets.QVBoxLayout(Interpretation)
        self.verticalLayoutRoot.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutRoot.setSpacing(0)
        self.verticalLayoutRoot.setObjectName("verticalLayoutRoot")
        self.splitterMain = QtWidgets.QSplitter(parent=Interpretation)
        self.splitterMain.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitterMain.setChildrenCollapsible(False)
        self.splitterMain.setHandleWidth(6)
        self.splitterMain.setObjectName("splitterMain")
        self.frameSignalsSidebar = QtWidgets.QFrame(parent=self.splitterMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSignalsSidebar.sizePolicy().hasHeightForWidth())
        self.frameSignalsSidebar.setSizePolicy(sizePolicy)
        self.frameSignalsSidebar.setMinimumSize(QtCore.QSize(260, 0))
        self.frameSignalsSidebar.setMaximumSize(QtCore.QSize(420, 16777215))
        self.frameSignalsSidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameSignalsSidebar.setStyleSheet("QFrame#frameSignalsSidebar {\n"
"    background: rgba(18, 24, 38, 0.94);\n"
"    border-right: 1px solid rgba(96, 165, 250, 0.20);\n"
"}\n"
"QPushButton#btnRecordSignal, QPushButton#btnOpenSignalFiles, QPushButton#btnChooseSignalFolder {\n"
"    min-height: 42px;\n"
"    border-radius: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 8px 12px;\n"
"}\n"
"QPushButton#btnRecordSignal {\n"
"    background: rgba(230, 168, 72, 0.18);\n"
"    border: 1px solid rgba(230, 168, 72, 0.40);\n"
"}\n"
"QPushButton#btnOpenSignalFiles {\n"
"    background: rgba(96, 165, 250, 0.16);\n"
"    border: 1px solid rgba(96, 165, 250, 0.40);\n"
"}\n"
"QPushButton#btnChooseSignalFolder {\n"
"    background: rgba(74, 222, 128, 0.14);\n"
"    border: 1px solid rgba(74, 222, 128, 0.35);\n"
"}\n"
"QListWidget#listWidgetSignals {\n"
"    border: 1px solid rgba(148, 163, 184, 0.22);\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    outline: none;\n"
"}\n"
"QListWidget#listWidgetSignals::item {\n"
"    min-height: 32px;\n"
"    border-radius: 8px;\n"
"    padding: 6px 8px;\n"
"}\n"
"QListWidget#listWidgetSignals::item:selected {\n"
"    background: rgba(96, 165, 250, 0.22);\n"
"}\n"
"QFrame#frameSignalMeta {\n"
"    background: rgba(30, 41, 59, 0.85);\n"
"    border: 1px solid rgba(148, 163, 184, 0.18);\n"
"    border-radius: 12px;\n"
"}\n"
"QLabel#labelSignalMetaTitle {\n"
"    font-size: 12px;\n"
"    font-weight: 700;\n"
"    color: rgba(226, 232, 240, 0.94);\n"
"}\n"
"QLabel#labelSignalMetaValue {\n"
"    font-size: 12px;\n"
"    color: rgba(226, 232, 240, 0.72);\n"
"}")
        self.frameSignalsSidebar.setObjectName("frameSignalsSidebar")
        self.verticalLayoutSidebar = QtWidgets.QVBoxLayout(self.frameSignalsSidebar)
        self.verticalLayoutSidebar.setContentsMargins(18, 18, 18, 18)
        self.verticalLayoutSidebar.setSpacing(14)
        self.verticalLayoutSidebar.setObjectName("verticalLayoutSidebar")
        self.labelSignalsListTitle = QtWidgets.QLabel(parent=self.frameSignalsSidebar)
        self.labelSignalsListTitle.setStyleSheet("font-size: 20px; font-weight: 700;")
        self.labelSignalsListTitle.setObjectName("labelSignalsListTitle")
        self.verticalLayoutSidebar.addWidget(self.labelSignalsListTitle)
        self.labelSignalsListHint = QtWidgets.QLabel(parent=self.frameSignalsSidebar)
        self.labelSignalsListHint.setWordWrap(True)
        self.labelSignalsListHint.setStyleSheet("font-size: 13px; color: rgba(226, 232, 240, 0.78);")
        self.labelSignalsListHint.setObjectName("labelSignalsListHint")
        self.verticalLayoutSidebar.addWidget(self.labelSignalsListHint)
        self.labelSignalFolderPath = QtWidgets.QLabel(parent=self.frameSignalsSidebar)
        self.labelSignalFolderPath.setWordWrap(True)
        self.labelSignalFolderPath.setStyleSheet("font-size: 12px; color: rgba(226, 232, 240, 0.62);")
        self.labelSignalFolderPath.setObjectName("labelSignalFolderPath")
        self.verticalLayoutSidebar.addWidget(self.labelSignalFolderPath)
        self.btnChooseSignalFolder = QtWidgets.QPushButton(parent=self.frameSignalsSidebar)
        self.btnChooseSignalFolder.setObjectName("btnChooseSignalFolder")
        self.verticalLayoutSidebar.addWidget(self.btnChooseSignalFolder)
        self.listWidgetSignals = QtWidgets.QListWidget(parent=self.frameSignalsSidebar)
        self.listWidgetSignals.setObjectName("listWidgetSignals")
        self.verticalLayoutSidebar.addWidget(self.listWidgetSignals)
        self.frameSignalMeta = QtWidgets.QFrame(parent=self.frameSignalsSidebar)
        self.frameSignalMeta.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameSignalMeta.setObjectName("frameSignalMeta")
        self.verticalLayoutSignalMeta = QtWidgets.QVBoxLayout(self.frameSignalMeta)
        self.verticalLayoutSignalMeta.setContentsMargins(12, 10, 12, 10)
        self.verticalLayoutSignalMeta.setSpacing(6)
        self.verticalLayoutSignalMeta.setObjectName("verticalLayoutSignalMeta")
        self.labelSignalMetaTitle = QtWidgets.QLabel(parent=self.frameSignalMeta)
        self.labelSignalMetaTitle.setObjectName("labelSignalMetaTitle")
        self.verticalLayoutSignalMeta.addWidget(self.labelSignalMetaTitle)
        self.labelSignalMetaValue = QtWidgets.QLabel(parent=self.frameSignalMeta)
        self.labelSignalMetaValue.setWordWrap(True)
        self.labelSignalMetaValue.setObjectName("labelSignalMetaValue")
        self.verticalLayoutSignalMeta.addWidget(self.labelSignalMetaValue)
        self.verticalLayoutSidebar.addWidget(self.frameSignalMeta)
        self.btnOpenSignalFiles = QtWidgets.QPushButton(parent=self.frameSignalsSidebar)
        self.btnOpenSignalFiles.setObjectName("btnOpenSignalFiles")
        self.verticalLayoutSidebar.addWidget(self.btnOpenSignalFiles)
        self.btnRecordSignal = QtWidgets.QPushButton(parent=self.frameSignalsSidebar)
        self.btnRecordSignal.setObjectName("btnRecordSignal")
        self.verticalLayoutSidebar.addWidget(self.btnRecordSignal)
        self.scrollArea = ScrollArea(parent=self.splitterMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setAcceptDrops(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrlAreaSignals = QtWidgets.QWidget()
        self.scrlAreaSignals.setGeometry(QtCore.QRect(0, 0, 546, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrlAreaSignals.sizePolicy().hasHeightForWidth())
        self.scrlAreaSignals.setSizePolicy(sizePolicy)
        self.scrlAreaSignals.setAutoFillBackground(True)
        self.scrlAreaSignals.setObjectName("scrlAreaSignals")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrlAreaSignals)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.scrlAreaSignals)
        self.splitter.setStyleSheet("QSplitter::handle:vertical {\n"
"margin: 4px 0px;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"stop:0 rgba(255, 255, 255, 0),\n"
"stop:0.5 rgba(100, 100, 100, 100),\n"
"stop:1 rgba(255, 255, 255, 0));\n"
"    image: url(:/icons/icons/splitter_handle_horizontal.svg);\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.labelGettingStarted = QtWidgets.QLabel(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.labelGettingStarted.setFont(font)
        self.labelGettingStarted.setStyleSheet("padding: 36px;\n"
"color: rgba(226, 232, 240, 0.9);")
        self.labelGettingStarted.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelGettingStarted.setWordWrap(True)
        self.labelGettingStarted.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.labelGettingStarted.setObjectName("labelGettingStarted")
        self.placeholderLabel = QtWidgets.QLabel(parent=self.splitter)
        self.placeholderLabel.setText("")
        self.placeholderLabel.setObjectName("placeholderLabel")
        self.verticalLayout.addWidget(self.splitter)
        self.scrollArea.setWidget(self.scrlAreaSignals)
        self.verticalLayoutRoot.addWidget(self.splitterMain)

        self.retranslateUi(Interpretation)

    def retranslateUi(self, Interpretation):
        _translate = QtCore.QCoreApplication.translate
        Interpretation.setWindowTitle(_translate("Interpretation", "Form"))
        self.labelSignalsListTitle.setText(_translate("Interpretation", "Сигналы"))
        self.labelSignalsListHint.setText(_translate("Interpretation", "Выбери файл из списка. Справа откроется его окно с обычными кнопками и просмотром."))
        self.labelSignalFolderPath.setText(_translate("Interpretation", "Папка сигналов: не выбрана"))
        self.btnChooseSignalFolder.setText(_translate("Interpretation", "Выбрать папку с сигналами"))
        self.labelSignalMetaTitle.setText(_translate("Interpretation", "Сведения о записи"))
        self.labelSignalMetaValue.setText(_translate("Interpretation", "Файл пока не выбран. Открой запись или выбери её в списке."))
        self.btnOpenSignalFiles.setText(_translate("Interpretation", "Выбрать файл сигнала"))
        self.btnRecordSignal.setText(_translate("Interpretation", "Записать сигнал"))
        self.labelGettingStarted.setText(_translate("Interpretation", "<html><head/><body><p align=\"center\">Открой или запиши сигнал слева, чтобы начать работу.</p><p align=\"center\"><span style=\" font-size:12pt; color:#94a3b8;\">После выбора записи здесь появятся график, параметры и содержимое сигнала.</span></p></body></html>"))
from urh.ui.ScrollArea import ScrollArea
